version: '2'
services:
  budget-app:
    image: budget
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://budget-postgresql:5432/budget
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://budget-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://budget-elasticsearch:9200
    ports:
      - 8080:8080
  budget-postgresql:
    extends:
      file: postgresql.yml
      service: budget-postgresql
  budget-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: budget-elasticsearch
